### ISSUE TITLE
Removal of the w3centities-f.ent from http://www.w3.org/2003/entities/2007/w3centities-f.ent

### ISSUE THREAD

**Issue by raghav-vk** [w3c/xml-entities#1]
Since Then I have downloaded the w3centities-f.ent from here and create a local System path for the validation. However the I am not having success with the change. I keep getting this error 

-//W3C//ENTITIES Combined Set//EN//XML; Line #1; Column #3; The markup declarations contained or pointed to by the document type declaration must be well-formed.

My docType is this:

```
<!DOCTYPE html [
  <!ENTITY % w3centities-f PUBLIC "-//W3C//ENTITIES Combined Set//EN//XML" "http://127.0.0.1:8080/alfresco/dtd/w3centities-f.ent">
%w3centities-f;
]>
```

Any ideas what could be wrong is this dtd exactly same as the one that was on w3.org ?

**Comment by davidcarlisle** [comment]
That's odd, the file has not changed. Can you diff your copy against the previous version?

**Comment by davidcarlisle** [comment]
no feedback for over 4 years, closing. Please re-open if there is still an issue.
