### ISSUE TITLE
Inconsistency on 2007doc/byalpha.html

### ISSUE THREAD

**Issue by andrecbarros** [w3c/xml-entities#2]
For entities \&acirc; and \&Acirc; the first description of them is inverted (small/capital); the Unicode description, though, is correct.

**Comment by davidcarlisle** [comment]
@andrecbarros  sorry this comment got completely missed. You are of course right.
I'll fix at source here and also in https://github.com/mathml-refresh/xml-entities/
Not sure yet when an updated publication will appear.
